In [126]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/fandbdataset/DataFB.csv


In [127]:
import pandas as pd
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [128]:
df = pd.read_csv('../input/fandbdataset/DataFB.csv')
df.head()

Emitten          DER  Operating Profit Margin  Return on Assets  \
0    DMND  4449.058000               165.027000              0.24   
1    PCAR    33.821513               -11.714724              0.56   
2    ADES   485.384000                74.384000              0.39   
3    AISA   951.024000               -59.633000             -2.54   
4    ALTO   238.218141                -8.280273              1.96   

   Sales Growth  Category  
0          0.04         2  
1         -0.14         1  
2          0.11         2  
3         -0.04         3  
4         -0.01         3

In [129]:
np.asarray(df)

array([['DMND', 4449.058, 165.027, 0.24, 0.04, 2],
       ['PCAR', 33.821513127, -11.714723668, 0.56, -0.14, 1],
       ['ADES', 485.384, 74.384, 0.39, 0.11, 2],
       ['AISA', 951.024, -59.633, -2.54, -0.04, 3],
       ['ALTO', 238.218140938, -8.280272626, 1.96, -0.01, 3],
       ['BTEK', 922.796006711, -372.055131717, 1.73, -0.1, 1],
       ['BUDI', 1804.295, 21.837, 1.29, 0.01, 3],
       ['CAMP', 712.510757409, 22.82556318, 0.14, 0.03, 3],
       ['CEKA', 2510.134429334, 115.36764037, 0.17, 0.11, 2],
       ['CLEO', 719.792908778, 94.281204735, 0.54, 0.1, 2],
       ['COCO', 98.897789526, 1.729820915, 1.41, 0.01, 3],
       ['DLTA', 349.070293, 70.526147, 0.23, 0.08, 2],
       ['ENZO', 315.761662236, 2.638729723, 0.73, 0.01, 3],
       ['FOOD', 69.413078667, -5.554043614, 0.74, -0.05, 3],
       ['GOOD', 5740.689796963, 197.434505066, 0.9, 0.06, 2],
       ['HOKI', 936.570659004, 28.5907008, 0.38, 0.04, 2],
       ['ICBP', 33896.887, 4337.822, 1.14, 0.05, 4],
       ['IKAN', 60.5

In [130]:
import statsmodels.api as sm

In [131]:
df.drop(['Emitten'], axis=1, inplace=True)

In [132]:
scaler = StandardScaler()

X = scaler.fit_transform(x)

In [133]:
X

array([[-8.73451081e-02, -2.29009646e-01, -4.34714453e-01,
         1.27286754e-01],
       [-3.98635216e-01, -3.59121604e-01, -7.38619888e-02,
        -2.05477189e+00],
       [-3.66798431e-01, -2.95738305e-01, -2.65564861e-01,
         9.75865115e-01],
       [-3.33969130e-01, -3.94397602e-01, -3.56962024e+00,
        -8.42517087e-01],
       [-3.84224516e-01, -3.56593264e-01,  1.50486754e+00,
        -4.78840647e-01],
       [-3.35959305e-01, -6.24393408e-01,  1.24550483e+00,
        -1.56986997e+00],
       [-2.73810445e-01, -3.34421831e-01,  7.49332696e-01,
        -2.36389686e-01],
       [-3.50785174e-01, -3.33694080e-01, -5.47480848e-01,
         6.06127401e-03],
       [-2.24046218e-01, -2.65567377e-01, -5.13650930e-01,
         9.75865115e-01],
       [-3.50271756e-01, -2.81090579e-01, -9.64152678e-02,
         8.54639635e-01],
       [-3.94047103e-01, -3.49224133e-01,  8.84652370e-01,
        -2.36389686e-01],
       [-3.76409039e-01, -2.98578340e-01, -4.45991093e-01,
      

In [134]:
x = df.drop('Category', axis=1)
x.head()

DER  Operating Profit Margin  Return on Assets  Sales Growth
0  4449.058000               165.027000              0.24          0.04
1    33.821513               -11.714724              0.56         -0.14
2   485.384000                74.384000              0.39          0.11
3   951.024000               -59.633000             -2.54         -0.04
4   238.218141                -8.280273              1.96         -0.01

In [135]:
y = df['Category']
y.head()

0    2
1    1
2    2
3    3
4    3
Name: Category, dtype: int64

In [136]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [137]:
x_train_sm = sm.add_constant(x_train)
x_train_sm

const           DER  Operating Profit Margin  Return on Assets  \
19    1.0    687.780895               119.184784              0.42   
10    1.0     98.897790                 1.729821              1.41   
1     1.0     33.821513               -11.714724              0.56   
2     1.0    485.384000                74.384000              0.39   
9     1.0    719.792909                94.281205              0.54   
8     1.0   2510.134429               115.367640              0.17   
4     1.0    238.218141                -8.280273              1.96   
18    1.0  58775.946000              4729.034000              1.15   
0     1.0   4449.058000               165.027000              0.24   
11    1.0    349.070293                70.526147              0.23   
5     1.0    922.796007              -372.055132              1.73   
3     1.0    951.024000               -59.633000             -2.54   
17    1.0     60.593691                -1.254946              0.93   
15    1.0    936.570659                28.590701              0.38   
16    1.0  33896.887000              4337.822000              1.14   
7     1.0    712.510757                22.825563              0.14   

    Sales Growth  
19          0.26  
10          0.01  
1          -0.14  
2           0.11  
9           0.10  
8           0.11  
4          -0.01  
18          0.03  
0           0.04  
11          0.08  
5          -0.10  
3          -0.04  
17         -0.01  
15          0.04  
16          0.05  
7           0.03

In [138]:
#logit_mod = sm.Logit(y_train, x_train_sm
                     
mnlogit_mod = sm.MNLogit(y_train, x_train_sm)
mnlogit_fit = mnlogit_mod.fit()

         Current function value: 0.745322
         Iterations: 35


/opt/conda/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)


In [139]:
print (mnlogit_fit.summary())

                          MNLogit Regression Results                          
Dep. Variable:               Category   No. Observations:                   16
Model:                        MNLogit   Df Residuals:                        1
Method:                           MLE   Df Model:                           12
Date:                Wed, 06 Jul 2022   Pseudo R-squ.:                  0.4043
Time:                        13:52:23   Log-Likelihood:                -11.925
converged:                      False   LL-Null:                       -20.018
Covariance Type:            nonrobust   LLR p-value:                    0.1828
             Category=2       coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       1.0005      1.453      0.689      0.491      -1.847       3.848
DER                        -0.0002      0.001     -0.355      0.723      -0.001       0.001


In [140]:
model = LogisticRegression(multi_class='ovr')
model.fit(x_train, y_train)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(multi_class='ovr')

In [141]:
model.predict_proba(x_test)[0:5]

array([[1.64155302e-01, 3.76279836e-01, 4.59564456e-01, 4.05706370e-07],
       [1.36131243e-01, 3.29835320e-01, 5.34033018e-01, 4.18680453e-07],
       [5.97709804e-01, 4.02290023e-01, 1.57091518e-07, 1.64240486e-08],
       [4.58350383e-01, 5.25065955e-01, 1.65835151e-02, 1.47163045e-07]])

In [142]:
predictions = model.predict(x_test)
predictions

array([3, 3, 1, 2])

In [143]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         1
           3       1.00      0.67      0.80         3

    accuracy                           0.50         4
   macro avg       0.33      0.22      0.27         4
weighted avg       0.75      0.50      0.60         4



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [144]:
print(accuracy_score(y_test, predictions))

0.5
